import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useAuth } from "../hooks/AuthContext";
import { signInGoogle, signOutGoogle } from "../lib/googleAuth";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { signIn, signOut, isAuthenticated, user } = useAuth();
  const handleSignIn = () => {
    signIn();
  };
  const handleSignOut = () => {
    console.log("sign out", isAuthenticated);

    signOut();
  };
  console.log(isAuthenticated);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>HELLO</h1>
        <button onClick={handleSignIn}>Sign in</button>
        <button onClick={handleSignOut}>Sign out</button>
        <button onClick={() => console.log(isAuthenticated, user)}>
          authenticated?
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
